# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/snake_upd.xdc

# Block Designs: bd/snake_hw/snake_hw.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw || ORIG_REF_NAME==snake_hw} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_microblaze_0_0/snake_hw_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_microblaze_0_0 || ORIG_REF_NAME==snake_hw_microblaze_0_0} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_microblaze_0_axi_periph_1/snake_hw_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_microblaze_0_axi_periph_1 || ORIG_REF_NAME==snake_hw_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_microblaze_0_axi_intc_0/snake_hw_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_microblaze_0_axi_intc_0 || ORIG_REF_NAME==snake_hw_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_microblaze_0_xlconcat_0/snake_hw_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_microblaze_0_xlconcat_0 || ORIG_REF_NAME==snake_hw_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_mdm_1_1/snake_hw_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_mdm_1_1 || ORIG_REF_NAME==snake_hw_mdm_1_1} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_clk_wiz_1_1/snake_hw_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_clk_wiz_1_1 || ORIG_REF_NAME==snake_hw_clk_wiz_1_1} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_rst_clk_wiz_1_100M_1/snake_hw_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==snake_hw_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_axi_uartlite_0_1/snake_hw_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_axi_uartlite_0_1 || ORIG_REF_NAME==snake_hw_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_axi_gpio_0_0/snake_hw_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_axi_gpio_0_0 || ORIG_REF_NAME==snake_hw_axi_gpio_0_0} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_xbar_0/snake_hw_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_xbar_0 || ORIG_REF_NAME==snake_hw_xbar_0} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_dlmb_v10_1/snake_hw_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_dlmb_v10_1 || ORIG_REF_NAME==snake_hw_dlmb_v10_1} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_ilmb_v10_1/snake_hw_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_ilmb_v10_1 || ORIG_REF_NAME==snake_hw_ilmb_v10_1} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_dlmb_bram_if_cntlr_1/snake_hw_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==snake_hw_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_ilmb_bram_if_cntlr_1/snake_hw_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==snake_hw_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_lmb_bram_1/snake_hw_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_lmb_bram_1 || ORIG_REF_NAME==snake_hw_lmb_bram_1} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_VGA_transmitter_0_1/snake_hw_VGA_transmitter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_VGA_transmitter_0_1 || ORIG_REF_NAME==snake_hw_VGA_transmitter_0_1} -quiet] -quiet

# IP: bd/snake_hw/ip/snake_hw_c_counter_binary_0_0/snake_hw_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==snake_hw_c_counter_binary_0_0 || ORIG_REF_NAME==snake_hw_c_counter_binary_0_0} -quiet] -quiet

# XDC: bd/snake_hw/snake_hw_ooc.xdc
