# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: w:/snake/project_1/project_1.srcs/sources_1/bd/snake_hw/ip/snake_hw_ilmb_bram_if_cntlr_1/snake_hw_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'snake_hw_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/snake/project_1/project_1.srcs/sources_1/bd/snake_hw/ip/snake_hw_ilmb_bram_if_cntlr_1/snake_hw_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'snake_hw_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: w:/snake/project_1/project_1.srcs/sources_1/bd/snake_hw/ip/snake_hw_ilmb_bram_if_cntlr_1/snake_hw_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'snake_hw_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: w:/snake/project_1/project_1.srcs/sources_1/bd/snake_hw/ip/snake_hw_ilmb_bram_if_cntlr_1/snake_hw_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'snake_hw_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
